name: CI

on:
  push:
    branches: [ "test" ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "registryneuaks01"
  CONTAINER_NAME: "rx-content-test"
  RESOURCE_GROUP: "rg-neu-n-dataapps-01"
  WEB_APP_NAME: "rx-ai-content-gen-test"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NON_PROD }}
        
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{env.CONTAINER_NAME}}:${{ github.sha }} \
                       --registry ${{ env.AZURE_CONTAINER_REGISTRY }} \
                       -g ${{ env.RESOURCE_GROUP }} \
                       --agent-pool nonprodneuacrpool \
                       .

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: self-hosted
    needs: [buildImage]

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NON_PROD }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ${{ env.WEB_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --container-image-name registryneuaks01.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} \
            --container-registry-url https://registryneuaks01.azurecr.io \
            --container-registry-user registryneuaks01 \
            --container-registry-password ${{ secrets.ACR_PASSWORD_NON_PROD }}