name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "neupaksregistry01"
  CONTAINER_NAME: "rx-ai-content-gen-dev"
  RESOURCE_GROUP: "rg-neu-p-dataapps-01"
  WEB_APP_NAME: "rx-ai-content-gen-dev"

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: [self-hosted, prod-runner]

    steps:
      # Logs in with your Azure credentials
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
        
      # Builds and pushes an image up to your Azure Container Registry
      - name: Build and push image to ACR
        run: |
          az acr build --image ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{env.CONTAINER_NAME}}:${{ github.sha }} --registry ${{ env.AZURE_CONTAINER_REGISTRY }} -g ${{ env.RESOURCE_GROUP }} --agent-pool prodneuacrpool   .

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: [self-hosted, prod-runner]
    needs: [buildImage]

    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ${{ env.WEB_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --container-image-name neupaksregistry01.azurecr.io/${{ env.CONTAINER_NAME }}:${{ github.sha }} \
            --container-registry-url https://neupaksregistry01.azurecr.io \
            --container-registry-user neupaksregistry01 \
            --container-registry-password ${{ secrets.ACR_PASSWORD }}
            